import type { AuditPort, AuditParams, Repository } from "@primebrick/dal-pg";
import { AuditLogEntity } from "@primebrick/dal-pg";

export class BeAuditPortAdapter implements AuditPort {
  constructor(private repo: Repository) {}

  async writeAudit(params: AuditParams): Promise<void> {
    // AuditParams contains: entityClassName, tableName (e.g. "customers"),
    //   entityId, entityUuid, action, changedAt, version, changedBy, delta
    //
    // The audit table name is derived by appending "_audit" to the entity table name.
    // This convention is explicit here (single source of truth) and matches the
    // BE's existing AuditService behavior: `${getTableName(entityClass)}_audit`.
    const auditTableName = `${params.tableName}_audit`;

    await this.repo.add(AuditLogEntity, {
      entity_id: params.entityId,
      entity_uuid: params.entityUuid,
      action: params.action,
      changed_at: params.changedAt,
      changed_by: params.changedBy,
      version: params.version,
      delta: params.delta,
    }, { tableName: auditTableName });
    // No audit port passed → no recursive audit writing.
    // AuditLogEntity has no @AuditableField → no audit stamping.
    // id is identity PK → auto-generated by DB.
  }
}
