import type { AuditPort, AuditParams, Repository } from "@primebrick/dal-pg";
import { AuditLogEntity, AuditAction } from "@primebrick/dal-pg";
import { NatsClient, publishEntityChanged, type EntityChangedMarker } from "@primebrick/sdk";
import { getPresenceStore } from "../modules/collaboration/presence-store-holder.js";

/**
 * BE-side audit port adapter.
 *
 * Writes audit log rows to the per-entity audit table (`{tableName}_audit`)
 * and, for UPDATE / SOFT_DELETE / RESTORE / HARD_DELETE actions, publishes an
 * `EntityChangedMarker` via:
 *   1. Redis `setChanged(marker, 5min)` — so late-joining SSE clients see the
 *      most recent change without scanning the audit log.
 *   2. NATS `entity.{entityType}.{entityUuid}.changed` — so connected SSE
 *      clients on any BE instance receive a real-time `entity-changed` event.
 *
 * Both are best-effort: if Redis or NATS is unavailable, the marker is simply
 * not published. The audit log row itself is always written (that's the
 * primary responsibility of this adapter).
 */
export class BeAuditPortAdapter implements AuditPort {
  constructor(private repo: Repository) {}

  async writeAudit(params: AuditParams): Promise<void> {
    // AuditParams contains: entityClassName, tableName (e.g. "customers"),
    //   entityId, entityUuid, action, changedAt, version, changedBy, delta
    //
    // The audit table name is derived by appending "_audit" to the entity table name.
    // This convention is explicit here (single source of truth) and matches the
    // BE's existing AuditService behavior: `${getTableName(entityClass)}_audit`.
    const auditTableName = `${params.tableName}_audit`;

    const inserted = await this.repo.add(AuditLogEntity, {
      entity_id: params.entityId,
      entity_uuid: params.entityUuid,
      action: params.action,
      changed_at: params.changedAt,
      changed_by: params.changedBy,
      version: params.version,
      delta: params.delta,
    }, { tableName: auditTableName });
    // No audit port passed → no recursive audit writing.
    // AuditLogEntity has no @AuditableField → no audit stamping.
    // id is identity PK → auto-generated by DB.

    // ─── Entity-changed hook ───────────────────────────────────────────
    // Fire after the audit row is committed. Only for actions that change
    // the entity state (not INSERT — a new entity has no concurrent viewers).
    if (
      params.action === AuditAction.UPDATE ||
      params.action === AuditAction.SOFT_DELETE ||
      params.action === AuditAction.RESTORE ||
      params.action === AuditAction.HARD_DELETE
    ) {
      const marker: EntityChangedMarker = {
        entity_type: params.tableName, // e.g. "customers"
        entity_uuid: params.entityUuid,
        version: params.version,
        audit_log_id: Number(inserted.id),
        changed_by: params.changedBy,
        changed_at: params.changedAt.getTime(),
      };

      // 1. Redis — store the marker with a 5-minute TTL
      try {
        const store = getPresenceStore();
        if (store) {
          await store.setChanged(marker, 300_000);
        }
      } catch {
        // best-effort: Redis unavailable
      }

      // 2. NATS — publish to entity.{entityType}.{entityUuid}.changed
      try {
        if (NatsClient.isConnected()) {
          await publishEntityChanged(NatsClient, marker);
        }
      } catch {
        // best-effort: NATS unavailable
      }
    }
  }
}
