-- Adds the mean-response-time label used by the speed score popover.
-- Idempotent: ON CONFLICT DO NOTHING.

INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('system.entities.ai_model.speed.avg_response', 'en-GB', 'Mean response time', NOW(), 'fire-and-forget', NOW(), 'fire-and-forget', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('system.entities.ai_model.speed.avg_response', 'it-IT', 'Tempo medio di risposta', NOW(), 'fire-and-forget', NOW(), 'fire-and-forget', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('system.entities.ai_model.speed.avg_response', 'fr-FR', 'Temps de réponse moyen', NOW(), 'fire-and-forget', NOW(), 'fire-and-forget', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('system.entities.ai_model.speed.avg_response', 'es-ES', 'Tiempo medio de respuesta', NOW(), 'fire-and-forget', NOW(), 'fire-and-forget', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('system.entities.ai_model.speed.avg_response', 'de-DE', 'Mittlere Antwortzeit', NOW(), 'fire-and-forget', NOW(), 'fire-and-forget', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('system.entities.ai_model.speed.avg_response', 'pt-PT', 'Tempo médio de resposta', NOW(), 'fire-and-forget', NOW(), 'fire-and-forget', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
