-- Fire-and-forget: badge values editor (TODO-style list) field labels and
-- tooltips on /configurations/create. All keys in system.translations,
-- 7 languages. Idempotent via partial unique index (key, language)
-- WHERE deleted_at IS NULL.

BEGIN;

INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES
  ('system.settings.config.typeConfig.badgeCode', 'en-GB', 'Badge code', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCode', 'en-US', 'Badge code', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCode', 'it-IT', 'Codice del badge', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCode', 'fr-FR', 'Code du badge', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCode', 'es-ES', 'Código del distintivo', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCode', 'de-DE', 'Badge-Code', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCode', 'pt-PT', 'Código do selo', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeHelp', 'en-GB', 'A unique code for this badge value — letters, numbers and underscores only (spaces become underscores), e.g. "active" or "NOT_COMPATIBLE".', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeHelp', 'en-US', 'A unique code for this badge value — letters, numbers and underscores only (spaces become underscores), e.g. "active" or "NOT_COMPATIBLE".', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeHelp', 'it-IT', 'Un codice univoco per questo valore del badge — solo lettere, numeri e underscore (gli spazi diventano underscore), es. "active" o "NOT_COMPATIBLE".', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeHelp', 'fr-FR', 'Un code unique pour cette valeur de badge — lettres, chiffres et underscores uniquement (les espaces deviennent des underscores), ex. "active" ou "NOT_COMPATIBLE".', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeHelp', 'es-ES', 'Un código único para este valor del distintivo — solo letras, números y guiones bajos (los espacios se convierten en guiones bajos), p. ej. "active" o "NOT_COMPATIBLE".', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeHelp', 'de-DE', 'Ein eindeutiger Code für diesen Badge-Wert — nur Buchstaben, Zahlen und Unterstriche (Leerzeichen werden zu Unterstrichen), z. B. "active" oder "NOT_COMPATIBLE".', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeHelp', 'pt-PT', 'Um código único para este valor do selo — apenas letras, números e underscores (espaços viram underscores), ex. "active" ou "NOT_COMPATIBLE".', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColor', 'en-GB', 'Color', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColor', 'en-US', 'Color', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColor', 'it-IT', 'Colore', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColor', 'fr-FR', 'Couleur', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColor', 'es-ES', 'Color', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColor', 'de-DE', 'Farbe', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColor', 'pt-PT', 'Cor', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColorHelp', 'en-GB', 'The badge''s background color.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColorHelp', 'en-US', 'The badge''s background color.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColorHelp', 'it-IT', 'Il colore di sfondo del badge.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColorHelp', 'fr-FR', 'La couleur de fond du badge.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColorHelp', 'es-ES', 'El color de fondo del distintivo.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColorHelp', 'de-DE', 'Die Hintergrundfarbe des Badges.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeColorHelp', 'pt-PT', 'A cor de fundo do selo.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKey', 'en-GB', 'Label (translation key)', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKey', 'en-US', 'Label (translation key)', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKey', 'it-IT', 'Etichetta (chiave di traduzione)', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKey', 'fr-FR', 'Libellé (clé de traduction)', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKey', 'es-ES', 'Etiqueta (clave de traducción)', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKey', 'de-DE', 'Beschriftung (Übersetzungsschlüssel)', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKey', 'pt-PT', 'Rótulo (chave de tradução)', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKeyHelp', 'en-GB', 'The text shown on the badge, as a translation key — a suggested key is pre-filled for this configuration.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKeyHelp', 'en-US', 'The text shown on the badge, as a translation key — a suggested key is pre-filled for this configuration.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKeyHelp', 'it-IT', 'Il testo mostrato sul badge, come chiave di traduzione — una chiave suggerita è precompilata per questa configurazione.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKeyHelp', 'fr-FR', 'Le texte affiché sur le badge, sous forme de clé de traduction — une clé suggérée est pré-remplie pour cette configuration.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKeyHelp', 'es-ES', 'El texto que se muestra en el distintivo, como clave de traducción — se prellena una clave sugerida para esta configuración.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKeyHelp', 'de-DE', 'Der auf dem Badge angezeigte Text als Übersetzungsschlüssel — ein vorgeschlagener Schlüssel ist für diese Konfiguration vorausgefüllt.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeLabelKeyHelp', 'pt-PT', 'O texto mostrado no selo, como chave de tradução — uma chave sugerida é pré-preenchida para esta configuração.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeDuplicate', 'en-GB', 'This code already exists.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeDuplicate', 'en-US', 'This code already exists.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeDuplicate', 'it-IT', 'Questo codice esiste già.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeDuplicate', 'fr-FR', 'Ce code existe déjà.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeDuplicate', 'es-ES', 'Este código ya existe.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeDuplicate', 'de-DE', 'Dieser Code existiert bereits.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeDuplicate', 'pt-PT', 'Este código já existe.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeAddTitle', 'en-GB', 'Add badge value', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeAddTitle', 'en-US', 'Add badge value', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeAddTitle', 'it-IT', 'Aggiungi valore badge', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeAddTitle', 'fr-FR', 'Ajouter une valeur de badge', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeAddTitle', 'es-ES', 'Añadir valor del distintivo', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeAddTitle', 'de-DE', 'Badge-Wert hinzufügen', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeAddTitle', 'pt-PT', 'Adicionar valor do selo', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeEditTitle', 'en-GB', 'Edit badge value', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeEditTitle', 'en-US', 'Edit badge value', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeEditTitle', 'it-IT', 'Modifica valore badge', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeEditTitle', 'fr-FR', 'Modifier la valeur de badge', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeEditTitle', 'es-ES', 'Editar valor del distintivo', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeEditTitle', 'de-DE', 'Badge-Wert bearbeiten', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeEditTitle', 'pt-PT', 'Editar valor do selo', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeInvalid', 'en-GB', 'Letters, numbers and underscores, all lowercase or all uppercase — e.g. active, NOT_COMPATIBLE, 1.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeInvalid', 'en-US', 'Letters, numbers and underscores, all lowercase or all uppercase — e.g. active, NOT_COMPATIBLE, 1.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeInvalid', 'it-IT', 'Lettere, numeri e underscore, tutto minuscolo o tutto maiuscolo — es. active, NOT_COMPATIBLE, 1.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeInvalid', 'fr-FR', 'Lettres, chiffres et underscores, tout en minuscules ou tout en majuscules — ex. active, NOT_COMPATIBLE, 1.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeInvalid', 'es-ES', 'Letras, números y guiones bajos, todo en minúsculas o todo en mayúsculas — p. ej. active, NOT_COMPATIBLE, 1.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeInvalid', 'de-DE', 'Buchstaben, Zahlen und Unterstriche, alles klein oder alles groß — z. B. active, NOT_COMPATIBLE, 1.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.badgeCodeInvalid', 'pt-PT', 'Letras, números e underscores, tudo minúsculo ou tudo maiúsculo — ex. active, NOT_COMPATIBLE, 1.', now(), 'initial-setup', now(), 'initial-setup', 1)
ON CONFLICT (key, language) WHERE deleted_at IS NULL DO UPDATE SET value = EXCLUDED.value, updated_at = now();

COMMIT;
