-- Fire-and-forget: widget configuration sections (URL / Phone / money
-- allowed_currencies) + dedicated validation-rule tooltips on
-- /configurations/create. All keys in system.translations, 7 languages.
-- Idempotent via the partial unique index (key, language) WHERE deleted_at IS NULL.

BEGIN;

INSERT INTO system.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES
  -- Section titles
  ('system.settings.config.typeConfig.urlConfig', 'en-GB', 'URL Configuration', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.urlConfig', 'en-US', 'URL Configuration', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.urlConfig', 'it-IT', 'Configurazione URL', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.urlConfig', 'fr-FR', 'Configuration URL', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.urlConfig', 'es-ES', 'Configuración de URL', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.urlConfig', 'de-DE', 'URL-Konfiguration', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.urlConfig', 'pt-PT', 'Configuração de URL', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.phoneConfig', 'en-GB', 'Phone Configuration', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.phoneConfig', 'en-US', 'Phone Configuration', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.phoneConfig', 'it-IT', 'Configurazione telefono', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.phoneConfig', 'fr-FR', 'Configuration du téléphone', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.phoneConfig', 'es-ES', 'Configuración del teléfono', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.phoneConfig', 'de-DE', 'Telefon-Konfiguration', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.phoneConfig', 'pt-PT', 'Configuração de telefone', now(), 'initial-setup', now(), 'initial-setup', 1),
  -- URL fields
  ('system.settings.config.typeConfig.allowedProtocols', 'en-GB', 'Allowed protocols', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocols', 'en-US', 'Allowed protocols', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocols', 'it-IT', 'Protocolli consentiti', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocols', 'fr-FR', 'Protocoles autorisés', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocols', 'es-ES', 'Protocolos permitidos', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocols', 'de-DE', 'Erlaubte Protokolle', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocols', 'pt-PT', 'Protocolos permitidos', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocolsHelp', 'en-GB', 'The protocols shown in the selector — the value can only use one of these.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocolsHelp', 'en-US', 'The protocols shown in the selector — the value can only use one of these.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocolsHelp', 'it-IT', 'I protocolli mostrati nel selettore — il valore può usare solo uno di questi.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocolsHelp', 'fr-FR', 'Les protocoles affichés dans le sélecteur — la valeur ne peut utiliser que l''un d''eux.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocolsHelp', 'es-ES', 'Los protocolos que se muestran en el selector — el valor solo puede usar uno de ellos.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocolsHelp', 'de-DE', 'Die im Auswahlfeld angezeigten Protokolle — der Wert darf nur eines davon verwenden.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedProtocolsHelp', 'pt-PT', 'Os protocolos mostrados no seletor — o valor só pode usar um deles.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocol', 'en-GB', 'Default protocol', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocol', 'en-US', 'Default protocol', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocol', 'it-IT', 'Protocollo predefinito', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocol', 'fr-FR', 'Protocole par défaut', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocol', 'es-ES', 'Protocolo predeterminado', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocol', 'de-DE', 'Standardprotokoll', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocol', 'pt-PT', 'Protocolo padrão', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocolHelp', 'en-GB', 'The protocol pre-selected when the field is empty.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocolHelp', 'en-US', 'The protocol pre-selected when the field is empty.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocolHelp', 'it-IT', 'Il protocollo preselezionato quando il campo è vuoto.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocolHelp', 'fr-FR', 'Le protocole présélectionné lorsque le champ est vide.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocolHelp', 'es-ES', 'El protocolo preseleccionado cuando el campo está vacío.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocolHelp', 'de-DE', 'Das vorausgewählte Protokoll, wenn das Feld leer ist.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultProtocolHelp', 'pt-PT', 'O protocolo pré-selecionado quando o campo está vazio.', now(), 'initial-setup', now(), 'initial-setup', 1),
  -- Phone fields
  ('system.settings.config.typeConfig.defaultCountry', 'en-GB', 'Default country', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountry', 'en-US', 'Default country', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountry', 'it-IT', 'Paese predefinito', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountry', 'fr-FR', 'Pays par défaut', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountry', 'es-ES', 'País predeterminado', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountry', 'de-DE', 'Standardland', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountry', 'pt-PT', 'País padrão', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountryHelp', 'en-GB', 'The calling-code prefix shown by default — e.g. +39 for Italy.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountryHelp', 'en-US', 'The calling-code prefix shown by default — e.g. +39 for Italy.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountryHelp', 'it-IT', 'Il prefisso telefonico mostrato di default — es. +39 per l''Italia.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountryHelp', 'fr-FR', 'L''indicatif téléphonique affiché par défaut — ex. +33 pour la France.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountryHelp', 'es-ES', 'El prefijo telefónico mostrado por defecto — p. ej. +34 para España.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountryHelp', 'de-DE', 'Die standardmäßig angezeigte Vorwahl — z. B. +49 für Deutschland.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCountryHelp', 'pt-PT', 'O prefixo telefónico mostrado por defeito — ex. +351 para Portugal.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountries', 'en-GB', 'Allowed countries', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountries', 'en-US', 'Allowed countries', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountries', 'it-IT', 'Paesi consentiti', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountries', 'fr-FR', 'Pays autorisés', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountries', 'es-ES', 'Países permitidos', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountries', 'de-DE', 'Erlaubte Länder', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountries', 'pt-PT', 'Países permitidos', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountriesHelp', 'en-GB', 'The countries shown in the prefix selector — leave empty to allow all.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountriesHelp', 'en-US', 'The countries shown in the prefix selector — leave empty to allow all.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountriesHelp', 'it-IT', 'I paesi mostrati nel selettore dei prefissi — lascia vuoto per consentirli tutti.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountriesHelp', 'fr-FR', 'Les pays affichés dans le sélecteur d''indicatif — laissez vide pour tous les autoriser.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountriesHelp', 'es-ES', 'Los países que se muestran en el selector de prefijos — deja vacío para permitir todos.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountriesHelp', 'de-DE', 'Die im Vorwahl-Auswahlfeld angezeigten Länder — leer lassen, um alle zu erlauben.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCountriesHelp', 'pt-PT', 'Os países mostrados no seletor de prefixos — deixe vazio para permitir todos.', now(), 'initial-setup', now(), 'initial-setup', 1),
  -- Money: allowed currencies
  ('system.settings.config.typeConfig.allowedCurrencies', 'en-GB', 'Allowed currencies', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrencies', 'en-US', 'Allowed currencies', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrencies', 'it-IT', 'Valute consentite', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrencies', 'fr-FR', 'Devises autorisées', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrencies', 'es-ES', 'Monedas permitidas', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrencies', 'de-DE', 'Erlaubte Währungen', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrencies', 'pt-PT', 'Moedas permitidas', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrenciesHelp', 'en-GB', 'The currencies the user can pick — leave empty to allow all.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrenciesHelp', 'en-US', 'The currencies the user can pick — leave empty to allow all.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrenciesHelp', 'it-IT', 'Le valute che l''utente può scegliere — lascia vuoto per consentirle tutte.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrenciesHelp', 'fr-FR', 'Les devises que l''utilisateur peut choisir — laissez vide pour toutes les autoriser.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrenciesHelp', 'es-ES', 'Las monedas que el usuario puede elegir — deja vacío para permitir todas.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrenciesHelp', 'de-DE', 'Die Währungen, die der Benutzer auswählen kann — leer lassen, um alle zu erlauben.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.allowedCurrenciesHelp', 'pt-PT', 'As moedas que o utilizador pode escolher — deixe vazio para permitir todas.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCurrencyHelp', 'en-GB', 'The currency pre-selected when the field is empty.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCurrencyHelp', 'en-US', 'The currency pre-selected when the field is empty.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCurrencyHelp', 'it-IT', 'La valuta preselezionata quando il campo è vuoto.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCurrencyHelp', 'fr-FR', 'La devise présélectionnée lorsque le champ est vide.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCurrencyHelp', 'es-ES', 'La moneda preseleccionada cuando el campo está vacío.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCurrencyHelp', 'de-DE', 'Die vorausgewählte Währung, wenn das Feld leer ist.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.defaultCurrencyHelp', 'pt-PT', 'A moeda pré-selecionada quando o campo está vazio.', now(), 'initial-setup', now(), 'initial-setup', 1),
  -- Dedicated validation-rule tooltips (were the generic optional marker)
  ('system.settings.config.typeConfig.minHelp', 'en-GB', 'The smallest value accepted — for text, the minimum number of characters.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.minHelp', 'en-US', 'The smallest value accepted — for text, the minimum number of characters.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.minHelp', 'it-IT', 'Il valore minimo accettato — per il testo, il numero minimo di caratteri.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.minHelp', 'fr-FR', 'La plus petite valeur acceptée — pour le texte, le nombre minimum de caractères.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.minHelp', 'es-ES', 'El valor más pequeño aceptado — para el texto, el número mínimo de caracteres.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.minHelp', 'de-DE', 'Der kleinste akzeptierte Wert — für Text die minimale Zeichenanzahl.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.minHelp', 'pt-PT', 'O menor valor aceite — para texto, o número mínimo de caracteres.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.maxHelp', 'en-GB', 'The largest value accepted — for text, the maximum number of characters.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.maxHelp', 'en-US', 'The largest value accepted — for text, the maximum number of characters.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.maxHelp', 'it-IT', 'Il valore massimo accettato — per il testo, il numero massimo di caratteri.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.maxHelp', 'fr-FR', 'La plus grande valeur acceptée — pour le texte, le nombre maximum de caractères.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.maxHelp', 'es-ES', 'El valor más grande aceptado — para el texto, el número máximo de caracteres.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.maxHelp', 'de-DE', 'Der größte akzeptierte Wert — für Text die maximale Zeichenanzahl.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.maxHelp', 'pt-PT', 'O maior valor aceite — para texto, o número máximo de caracteres.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternHelp', 'en-GB', 'An extra rule to validate complex values — e.g. a VAT code or a password pattern.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternHelp', 'en-US', 'An extra rule to validate complex values — e.g. a VAT code or a password pattern.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternHelp', 'it-IT', 'Una regola aggiuntiva per validare valori complessi — es. una partita IVA o un pattern per password.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternHelp', 'fr-FR', 'Une règle supplémentaire pour valider des valeurs complexes — ex. un numéro de TVA ou un format de mot de passe.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternHelp', 'es-ES', 'Una regla adicional para validar valores complejos — p. ej. un NIF o un patrón de contraseña.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternHelp', 'de-DE', 'Eine zusätzliche Regel zur Validierung komplexer Werte — z. B. eine USt-IdNr. oder ein Passwort-Muster.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternHelp', 'pt-PT', 'Uma regra extra para validar valores complexos — ex. um NIF ou um padrão de password.', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternPlaceholder', 'en-GB', 'e.g. ^\d+$ — only digits', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternPlaceholder', 'en-US', 'e.g. ^\d+$ — only digits', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternPlaceholder', 'it-IT', 'es. ^\d+$ — solo cifre', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternPlaceholder', 'fr-FR', 'ex. ^\d+$ — chiffres uniquement', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternPlaceholder', 'es-ES', 'p. ej. ^\d+$ — solo dígitos', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternPlaceholder', 'de-DE', 'z. B. ^\d+$ — nur Ziffern', now(), 'initial-setup', now(), 'initial-setup', 1),
  ('system.settings.config.typeConfig.regexPatternPlaceholder', 'pt-PT', 'ex. ^\d+$ — apenas dígitos', now(), 'initial-setup', now(), 'initial-setup', 1)
ON CONFLICT (key, language) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

COMMIT;
