-- Seed app.auth.login.mfa.challengeExpired (public.translations) — shown when
-- the MFA challenge token is expired/consumed (401 MFA_CHALLENGE_EXPIRED).
-- Added alongside the OTP input refresh flow (challenge/refresh endpoint).
INSERT INTO public.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('app.auth.login.mfa.challengeExpired', 'en-GB', 'Your sign-in session has expired. Please go back and log in again.', '2026-05-18T14:27:00Z', 'initial-setup', '2026-05-18T14:27:00Z', 'initial-setup', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO public.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('app.auth.login.mfa.challengeExpired', 'it-IT', 'La sessione di accesso è scaduta. Torna indietro ed effettua di nuovo l''accesso.', '2026-05-18T14:27:00Z', 'initial-setup', '2026-05-18T14:27:00Z', 'initial-setup', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO public.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('app.auth.login.mfa.challengeExpired', 'fr-FR', 'Votre session de connexion a expiré. Veuillez revenir en arrière et vous reconnecter.', '2026-05-18T14:27:00Z', 'initial-setup', '2026-05-18T14:27:00Z', 'initial-setup', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO public.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('app.auth.login.mfa.challengeExpired', 'es-ES', 'Tu sesión de inicio ha caducado. Vuelve atrás e inicia sesión de nuevo.', '2026-05-18T14:27:00Z', 'initial-setup', '2026-05-18T14:27:00Z', 'initial-setup', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO public.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('app.auth.login.mfa.challengeExpired', 'de-DE', 'Ihre Anmeldesitzung ist abgelaufen. Bitte gehen Sie zurück und melden Sie sich erneut an.', '2026-05-18T14:27:00Z', 'initial-setup', '2026-05-18T14:27:00Z', 'initial-setup', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
INSERT INTO public.translations (key, language, value, created_at, created_by, updated_at, updated_by, version) VALUES ('app.auth.login.mfa.challengeExpired', 'pt-PT', 'A sua sessão de início de sessão expirou. Volte atrás e inicie sessão novamente.', '2026-05-18T14:27:00Z', 'initial-setup', '2026-05-18T14:27:00Z', 'initial-setup', 1) ON CONFLICT (key, language) WHERE deleted_at IS NULL DO NOTHING;
