-- Add uuid column to role_mappings.
--
-- Following the standard Primebrick entity key convention (see organization_entity.ts
-- and user_profile_entity.ts), the internal bigserial PK `id` is never exposed
-- externally (FK joins only). The `uuid` column is the external-facing key used
-- for all API endpoints, audit fields, and the FE EntityListTable uid.
--
-- `idp_role` remains the Casdoor sync key (analogous to `idp_code` on orgs/users),
-- immutable after creation. The new `uuid` is generated by the DB on insert and
-- backfilled for existing rows.
--
-- NOTE: role_mappings uses HARD DELETE only (no deleted_at/deleted_by) because
-- Casdoor role deletion is irreversible — there is no Casdoor "restore role" API.

ALTER TABLE public.role_mappings
  ADD COLUMN IF NOT EXISTS uuid uuid DEFAULT gen_random_uuid() NOT NULL;

-- Backfill any existing rows that got NULL before the default was set
-- (shouldn't happen with DEFAULT + NOT NULL, but be safe).
UPDATE public.role_mappings
  SET uuid = gen_random_uuid()
  WHERE uuid IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "role_mappings_uuid_uq"
  ON "public"."role_mappings" ("uuid");
